### ISSUE TITLE
It hasn't worked since the update to 2.0.1

### ISSUE THREAD

**Issue by luisju73** [ha-termoweb/ha-termoweb#910]
### Home Assistant version

2026.1.2

### TermoWeb integration version

2.0.1

### Describe the bug

This error
Registrador: homeassistant.config_entries
Fuente: config_entries.py:3969
Ocurrió por primera vez: 09:06:23 (2 ocurrencias)
Última vez registrado: 09:07:30

Error occurred loading flow for integration termoweb: cannot import name 'SupportsDiagnostics' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

### Relevant logs

```shell

```
